std = "lua51"
max_line_length = false
exclude_files = {
	".luacheckrc"
}
ignore = {
	"11./SLASH_.*", -- Setting an undefined (Slash handler) global variable
	"11./BINDING_.*", -- Setting an undefined (Keybinding header) global variable
--	"113/LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
--	"113/NUM_LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
	"211", -- Unused local variable
	"211/L", -- Unused local variable "L"
	"211/CL", -- Unused local variable "CL"
	"212", -- Unused argument
	"213", -- Unused loop variable
--	"431", -- shadowing upvalue
	"43.", -- Shadowing an upvalue, an upvalue argument, an upvalue loop variable.
	"542", -- An empty if branch
}
globals = {
	"_G",
	"format",
	"wipe",
	"LibAddonManager",
	"max",
	"min",
	"CreateFrame",
	"IsShiftKeyDown",
	"IsControlKeyDown",
	"strtrim",
	"tinsert",
	"tremove",
	"strupper",
	"getglobal",
	"hooksecurefunc",
	"CloseDropDownMenus",
	"InterfaceOptions_AddCategory",
	"InterfaceOptionsFrame_OpenToCategory",
	"GetCurrentKeyBoardFocus",
	"strmatch",
	"UISpecialFrames",
	"UICreateInterfaceOptionPage_IsNewerVersion",
	"UICreateInterfaceOptionPage",
	"GameTooltip",
	"HIGHLIGHT_FONT_COLOR",
	"GRAY_FONT_COLOR",
	"GREEN_FONT_COLOR",
	"NORMAL_FONT_COLOR",
	"STANDARD_TEXT_FONT",
	"strsplit",
	"strlower",
	"strfind",
	"UIDropDownMenu_AddButton",
	"UIDropDownMenu_Initialize",
	"GetAddOnMetadata",
	"ClearOverrideBindings",
	"GetBindingKey",
	"SetOverrideBindingClick",
	"InCombatLockdown",
	"UnitName",
	"GetRealmName",
	"UnitFactionGroup",
	"UnitClass",
	"UnitGUID",
	"StaticPopup_Show",
	"StaticPopup_Hide",
	"StaticPopupDialogs",
	"GetNumGroupMembers",
	"IsInRaid",
	"UnitIsGroupLeader",
	"UnitIsRaidOfficer",
	"GetSpecialization",
	"DEFAULT_CHAT_FRAME",
	"SlashCmdList",
	"GetLocale",
	"OKAY",
	"YES",
	"NO",
	"ACCEPT",
	"CANCEL",
	"DECLINE",
	"UnitRace",
	"GetSpellInfo",
	"Pre80API",
	"GetTime",
	"GetSpellTabInfo",
	"IsPassiveSpell",
	"GetSpellBookItemInfo",
	"UnitCastingInfo",
	"UnitChannelInfo",
	"IsUsableSpell",
	"GetSpellCooldown",
	"IsSpellInRange",
	"HasPetSpells",
	"sort",
	"GetTalentInfo",
	"GetFlyoutInfo",
	"GetFlyoutSlotInfo",
	"GetSpecializationInfoByID",
	"BOOKTYPE_PET",
	"BOOKTYPE_SPELL",
	"MAX_TALENT_TIERS",
	"NUM_TALENT_COLUMNS",
	"IsAutoRepeatSpell",
	"floor",
	"UIParent",
	"GAME_VERSION_LABEL",
	"UICreateModularOptionFrame_IsNewerVersion",
	"UICreateModularOptionFrame",
	"UnitAura",
	"UnitBuff",
	"UnitDebuff",
	"UnitPosition",
	"C_Map",
	"MapUtil",
	"Enum",
	"PanelTemplates_TabResize",
	"UICreateTabFrame_IsNewerVersion",
	"UICreateTabFrame",
	"UnitAuraEx_GetVersion",
	"UnitAuraEx",
	"UnitBuffEx",
	"UnitDebuffEx",
	"GetCursorInfo",
	"ClearCursor",
	"GetSpellLink",
	"GetItemInfo",
	"GetItemQualityColor",
	"HandleModifiedItemClick",
	"UICreateVirtualScrollList_IsNewerVersion",
	"UICreateVirtualScrollList",
	"utf8_lc_uc",
	"utf8_uc_lc",
	"string.utf8len",
	"string.utf8sub",
	"string.utf8upper",
	"string.utf8lower",
	"string.utf8reverse",
	"CompactRaid",
	"LibStub",
	"CWDGMediaPack",
	"NAME",
	"DEFAULT",
	"NONE",
}